---
# ==> SELENIUM HUB
- name: create-dockerfile-selenium | Create Docker directory for selenium hub
  file:
    state: directory
    path: ./adop-docker-compose/selenium-hub
  tags:
    - selenium
  when: selenium == "enabled"

- name: create-dockerfile-selenium | Copy files to selenium hub folder
  shell: "cp -r ./roles/create-dockerfile-selenium/files/{{ item }} ./adop-docker-compose/selenium-hub/"
  with_items:
      - start-selenium-node.sh
      - start-xvfb.sh
  tags:
    - selenium
  when: selenium == "enabled"
   
- name: create-dockerfile-selenium | Create Dockerfile for selenium hub
  template:
    src: dockerfile-template-selenium-hub.j2
    dest: ./adop-docker-compose/selenium-hub/Dockerfile
  tags:
    - selenium
  when: selenium == "enabled"

# ==> SELENIUM NODE CHROME
- name: create-dockerfile-selenium | Create Docker directory for selenium node chrome
  file:
    state: directory
    path: ./adop-docker-compose/selenium-node-chrome
  tags:
    - selenium
  when: selenium == "enabled"

- name: create-dockerfile-selenium | Copy files to selenium node chrome folder
  shell: "cp -r ./roles/create-dockerfile-selenium/files/{{ item }} ./adop-docker-compose/selenium-node-chrome/"
  with_items:
      - wrap_chrome_binary
      - generate_config_chrome
  tags:
    - selenium
  when: selenium == "enabled"
   
- name: create-dockerfile-selenium | Create Dockerfile for selenium node chrome
  template:
    src: dockerfile-template-selenium-node-chrome.j2
    dest: ./adop-docker-compose/selenium-node-chrome/Dockerfile
  tags:
    - selenium
  when: selenium == "enabled"

# ==> SELENIUM NODE FIREFOX
- name: create-dockerfile-selenium | Create Docker directory for selenium node firefox
  file:
    state: directory
    path: ./adop-docker-compose/selenium-node-firefox
  tags:
    - selenium
  when: selenium == "enabled"

- name: create-dockerfile-selenium | Copy files to resources folder
  shell: "cp -r ./roles/create-dockerfile-selenium/files/generate_config_firefox ./adop-docker-compose/selenium-node-firefox/"
  tags:
    - selenium
  when: selenium == "enabled"
   
- name: create-dockerfile-selenium | Create Dockerfile for selenium node firefox
  template:
    src: dockerfile-template-selenium-node-firefox.j2
    dest: ./adop-docker-compose/selenium-node-firefox/Dockerfile
  tags:
    - selenium
  when: selenium == "enabled"
